<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;NU1605</NoWarn>
    <DebugType>portable</DebugType>
    <outputPath>..\..\bin\Debug\net461\plugins\</outputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;NU1605</NoWarn>
    <DebugType>portable</DebugType>
    <outputPath>..\..\bin\Release\net461\plugins\</outputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ExtLibs\MissionPlanner.Drawing\MissionPlanner.Drawing.csproj">
      <Aliases>Drawing</Aliases>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\ExtLibs\Utilities\MissionPlanner.Utilities.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\MissionPlanner.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Update="System.Windows.Forms">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BSE.Windows.Forms">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="GMap.NET.WindowsForms">
      <Version>1.7.5</Version>
    </PackageReference>
    <PackageReference Include="System.Drawing.Common">
      <Version>4.7.2</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
